services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
      - UPLOAD_LIMIT=500M
    restart: always
    ports:
      - 8080:80
    links:
      - mysql

  redis:
    image: redis
    restart: "no"
    ports:
      - "6379:6379"

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
